# Generated by Django 4.1.7 on 2023-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0033_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost_per_item',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
