# Generated by Django 4.1.7 on 2023-05-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0035_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
