# Generated by Django 4.1.7 on 2023-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0036_cart_customer_name_cart_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_sold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.IntegerField(default=1),
        ),
    ]
