# Generated by Django 4.1.7 on 2023-05-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0037_remove_orderitem_quantity_orderitem_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
