# Generated by Django 4.1.7 on 2023-05-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0039_rename_item_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='why_inventory.inventory'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
