# Generated by Django 4.1.7 on 2023-05-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('why_inventory', '0040_cart_customer_name_cart_paid_amount_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='bill',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='why_inventory.cart'),
        ),
    ]
